import kgf from "../../assets/Movie_images/kgf_1.jpg";
import kgf2 from "../../assets/Movie_images/kgf_2.jpg";
import jailer from "../../assets/Movie_images/jailer.jpg";
import kantara from "../../assets/Movie_images/kantara.jpg";
import rrr from "../../assets/Movie_images/rrr.jpg";
import pusha from "../../assets/Movie_images/pusha.jpg";
import eega from "../../assets/Movie_images/egga.jpg";
import salar from "../../assets/Movie_images/salar.jpg";
import ps1 from "../../assets/Movie_images/ps1.jpg";
import ps2 from "../../assets/Movie_images/ps2.jpg";

export const Movie_details = [
  {
    image: kgf,
    title: "KGF",
    id: 1,
    desc: "In the 1970s, a gangster named Rocky goes undercover as a slave to assassinate the owner of a notorious gold mine known as the Kolar Gold Fields.",
    director: "Prashanth Neel",
    producer: "Vijay Kiragandur",
    generes: "Action,Crime,Drama",
    year: "2018",
    stars: "Yash,Srinidhi Shetty",
    imdb_rating: "8.2",
    imdb_votes: "1,352",
    run: "2h 35m",
  },
  {
    image: kgf2,
    title: "KGF 2",
    id: 2,
    desc: "In the blood-soaked Kolar Gold Fields, Rocky's name strikes fear into his foes, while the government sees him as a threat to law and order. Rocky must battle threats from all sides for unchallenged supremacy.",
    director: "Prashanth Neel",
    producer: "Vijay Kiragandur",
    generes: "Action,Crime,Drama",
    year: "2022",
    stars: "Yash,Srinidhi Shetty,Sanjay Dutt",
    imdb_rating: "8.3",
    imdb_votes: "1,938",
    run: "2h 48m",
  },
  {
    image: rrr,
    title: "RRR",
    id: 3,
    desc: "A fictitious story about two legendary revolutionaries and their journey away from home before they started fighting for their country in the 1920s.",
    director: "S.S. Rajamouli",
    producer: "D.V.V Danayya",
    generes: "Action,Drama",
    year: "2022",
    stars: "Junior NTR,Ram Charan,Alia Bhatt",
    imdb_rating: "7.8",
    imdb_votes: "1.695",
    run: "3hr 7m",
  },
  {
    image: jailer,
    title: "Jailer",
    id: 4,
    desc: "A retired jailer goes on a manhunt to find his son's killers. But the road leads him to a familiar, albeit a bit darker place. Can he emerge from this complex situation successfully?",
    director: "Nelson Dilipkumar",
    producer: "Sun Network",
    generes: "Action,Comedy,Crime",
    year: "2023",
    stars: "Rajini,Shivanna,Mohanlal",
    imdb_rating: "7.1",
    imdb_votes: "1.600",
    run: "2hr 48m",
  },
  {
    image: kantara,
    title: "Kantara",
    id: 5,
    desc: "When greed paves the way for betrayal, scheming and murder, a young tribal reluctantly dons the traditions of his ancestors to seek justice.",
    director: "Rishab Shetty",
    producer: "Vijay Kiragandur",
    generes: "Action,Drama,Adventure",
    year: "2022",
    stars: "Rishab Shetty,Kishore,Saptami Gowda",
    imdb_rating: "8.2",
    imdb_votes: "1,243",
    run: "2hr 28m",
  },
  {
    image: pusha,
    title: "Pushpa The Rule",
    id: 6,
    desc: "A labourer rises through the ranks of a red sandal smuggling syndicate, making some powerful enemies in the process.",
    director: "Sukumar",
    producer: "Naveen Yemeni,Y Ravishankar",
    generes: "Action,Drama,Crime",
    year: "2021",
    stars: "Allu Arjun,Rashmika,Fahadh Faasil",
    imdb_rating: "7.6",
    imdb_votes: "933",
    run: "2hr 59m",
  },
  {
    image: eega,
    title: "Eega",
    id: 7,
    desc: "A murdered man is reincarnated as a housefly and seeks to avenge his death.",
    director: "S.S. Rajamouli",
    producer: "Daggubati Suresh Babu,Sai Korrapati",
    generes: "Action,Comedy,Drama",
    year: "2012",
    stars: "Kichcha Sudeep,Samantha,Nani",
    imdb_rating: "7.7",
    imdb_votes: "10,901",
    run: "2h 25m",
  },
  {
    image: salar,
    title: "Salaar",
    id: 8,
    desc: "A gang leader tries to keep a promise made to his dying friend and takes on the other criminal gangs.",
    director: "Prashanth Neel",
    producer: "Vijay Kiragandur",
    generes: "Action,Crime,Drama",
    year: "2023",
    stars: "Prabhas,Prithviraj Sukumar,Shruti Haasan",
    imdb_rating: "6.7",
    imdb_votes: "10,897",
    run: "2h 55m",
  },
  {
    image: ps1,
    title: "Ponniyan Selvan",
    id: 9,
    desc: "Vandiyathevan crosses the Chola land to deliver a message from the Crown Prince Aditha Karikalan, while Kundavai attempts to establish political peace as vassals and petty chieftains plot against the throne.",
    director: "Mani Ratnam",
    producer: "A Subaskaran",
    generes: "Action,Adventure,Drama",
    year: "2022",
    stars: "Vikram,Karthi,Jayam Ravi,Aishwarya Rai,Trisha",
    imdb_rating: "7.6",
    imdb_votes: "10,901",
    run: "2h 47",
  },
  {
    image: ps2,
    title: "Ponniyan Selvan 2",
    id: 10,
    desc: "Arulmozhi Varman continues on his journey to become Rajaraja I, the greatest ruler of the historic Chola empire of south India.",
    director: "Mani Ratnam",
    producer: "A Subaskaran",
    generes: "Action,Adventure,Drama",
    year: "2023",
    stars: "Vikram,Karthi,Jayam Ravi,Aishwarya Rai,Trisha",
    imdb_rating: "7.3",
    imdb_votes: "10,098",
    run: "2h 44m",
  },
];
