import asur_1 from "../../assets/Webseries_images/asur_1.jpg";
import asur_2 from "../../assets/Webseries_images/asur_2.jpg";
import dhootha from "../../assets/Webseries_images/dhootha.jpg";
import farzi from "../../assets/Webseries_images/farzi.jpg";
import fm1 from "../../assets/Webseries_images/fm_1.jpg";
import friends from "../../assets/Webseries_images/friends.jpg";
import kmv from "../../assets/Webseries_images/kmv.jpg";
import pan_1 from "../../assets/Webseries_images/panchayat_!.jpg";
import suz from "../../assets/Webseries_images/suzhal.jpg";
import scam1992 from "../../assets/Webseries_images/scam1992.jpg";
export const serieslist = [
  {
    image: asur_1,
    title: "Asur 1",
    id: 1,
    desc: "Shubh returns for revenge and this season he takes the challenge to a whole new level. With the heroes fallen apart, will a desolate Dhananjay Rajpoot and a torn Nikhil Nair be able to stop him?",
    director: "Gaurav",
    Streaming: "Jio Cinema",
    generes: "Crime,Mystery,Drama",
    year: "2020",
    stars: "Arshad Warsi,Barun Sobti,Anupriya",
    imdb_rating: "8.5",
    imdb_votes: "4,000",
    epi: "8",
  },
  {
    image: asur_2,
    title: "Asur 2",
    id: 2,
    desc: "Shubh returns for revenge and this season he takes the challenge to a whole new level. With the heroes fallen apart, will a desolate Dhananjay Rajpoot and a torn Nikhil Nair be able to stop him?",
    director: "Oni Sen",
    Streaming: "Jio Cinema",
    generes: "Crime,Mystery,Drama",
    year: "2023",
    stars: "Arshad Warsi,Barun Sobti,Anupriya",
    imdb_rating: "8.6",
    imdb_votes: "6,000",
    epi: "8",
  },
  {
    image: dhootha,
    title: "Dhootha",
    id: 3,
    desc: "In this supernatural thriller, journalist Sagar's life turns upside down when newspapers predict chilling incidents that unfold in his life.",
    director: "Oni Sen",
    Streaming: "Prime",
    generes: "Drama,Triller",
    year: "2023",
    stars: "Nagchaitanya,Parvathy",
    imdb_rating: "7.8",
    imdb_votes: "4,000",
    epi: "8",
  },
  {
    image: farzi,
    title:"Farzi",
    id: 4,
    desc: "An artist who gets pulled into the murky high stakes of a con job and a fiery task force officer on the mission to rid the country of his menaces in a fast-paced, edgy one-of-a-kind thriller.",
    director: "Raj & D.K",
    Streaming: "Prime",
    generes: "Crime,Drama,Triller",
    year: "2023",
    stars: "Shahid Kappor,Vijay Sethupathi,Bhuvan Arora",
    imdb_rating: "8.4",
    imdb_votes: "8,000",
    epi: "9",
  },
  {
    image: fm1,
    title:"The Family Man",
    id: 5,
    desc: "A working man from the National Investigation Agency tries to protect the nation from terrorism, but he also needs to keep his family safe from his secret job.",
    director: "",
    Streaming: "Prime",
    generes: "Crime,Drama,Triller",
    year: "2019",
    stars: "Mnaoj Bajpayee,Priyamani,Sharib,Samantha",
    imdb_rating: "8.7",
    imdb_votes: "9,000",
    epi: "4",
  },
  {
    image: friends,
    title:"Friends",
    id: 6,
    desc: "Follows the personal and professional lives of six twenty to thirty year-old friends living in the Manhattan borough of New York City.",
    director: "David Crane",
    Streaming: "Netflix",
    generes: "Crime,Drama,Triller",
    year: "1994-2004",
    stars: "Jennifer,Courteney,Lisa",
    imdb_rating: "8.9",
    imdb_votes: "2,000",
    epi: "236",
  },
  {
    image: kmv,
    title:"Koose Munisamy Veerappan",
    id: 7,
    desc: "This six-episode docu series looks at what happened in the case of the legendary sandalwood smuggler, poacher and terrorist Veerappan. It uses footage archived by Nakkheeran Gopal, editor and publisher of the Tamil journal Nakkheeran.",
    director: "Vasanth Balakrishnan",
    Streaming: "Zee 5",
    generes: "Crime,Documentary",
    year: "2023",
    stars: "Pa pa Mohan,Nakkheeran,Subramanyan",
    imdb_rating: "9.2",
    imdb_votes: "1,000",
    epi: "6",
  },
  {
    image: suz,
    title:"Suzhal - The Vortex",
    id: 8,
    desc: "In a small South Indian town, a seemingly routine minor case explodes into a twisted crime thriller that rips apart its social fabric.",
    director: "Gayatri",
    Streaming: "Prime",
    generes: "Crime,Drama,Triller",
    year: "2022",
    stars: "Kathir,Aishwaraya,Shreya",
    imdb_rating: "8.2",
    imdb_votes: "9,100",
    epi: "8",
  },
  {
    image: pan_1,
    title:"Panchayat",
    id: 9,
    desc: "A comedy-drama, which captures the journey of an engineering graduate Abhishek, who for lack of a better job option joins as secretary of a Panchayat office in a remote village of Uttar Pradesh.",
    director: "N.Nomesh Kumar",
    Streaming: "Prime",
    generes: "Crime,Drama,Triller",
    year: "2023",
    stars: "Jitendra,Raghubir,Neena Gupta",
    imdb_rating: "8.9",
    imdb_votes: "1,400",
    epi: "8",
  },


{
  image: scam1992,
  title:"Scam 1992",
  id: 10,
  desc: "The rise and fall of Harshad Mehta, a stockbroker who single-handedly took the stock market to great heights, is depicted",
  director: "Hansal Mehta",
  Streaming: "Sony Liv",
  generes: "Biography,Criem,Drama",
  year: "2020",
  stars: "Pratik Gandhi,Shreya,Hemant Kher",
  imdb_rating: "9.3",
  imdb_votes: "1,200",
  epi: "10",
},
];
